### PR TITLE
Update pdFPC.rst

### PR DESCRIPTION
**Pull request by givoltage**
added column that specifies the type of frame taken

### CODE REVIEW

**Comment by sbailey** [comment]
Great to be adding protoDESI files to the datamodel.  I hadn't realized that this was in here.  For consideration.

* This PR adds a "FRAMETYPE" column with example values "bias, dark, flat, object".  Klaus defined the equivalent concept for the DESI raw data as header keyword "OBSTYPE"; see [DESI-1229](https://desi.lbl.gov/DocDB/cgi-bin/private/ShowDocument?docid=1229).  We should use the same name for protoDESI.  Note: the offline pipeline has been using "FLAVOR" for this idea with somewhat different allowable values, but we're planning on switching to "OBSTYPE" for consistency.
* Similarly, Klaus defined TELRA and TELDEC instead of TEL-RA and TEL-DEC.

I'm sure there will end up being little inconsistencies between protoDESI and fullDESI, but let's not introduce ones that we know are different if there is no good reason for them to be different.  It is also ok to argue that the fullDESI description is the one that should change, but that should be explicit.

I think the "required columns" described here are actually supposed to be FITS header keywords?  The description here makes them sounds like they are columns of a binary table, but that can't be in HDU0 and most/all values are just one number per exposure (e.g. TELRA, TELDEC).  When other data model files say "Required Header Keywords" it means that DESI requires these to exist, not that the FITS standard requires these to exist.

If these are indeed header keywords, then that is another reason for FRAMETYPE -> OBSTYPE due to the 8-character limit of FITS header keywords.

**Comment by weaverba137** [comment]
Indeed, the existing file needs some work.  It looks like it was just copy-and-pasted rather than being based on the actual file.

**Comment by sbailey** [comment]
@givoltage FYI, if you have an existing FITS file that you want to document, `desidatamodel/bin/generate_model` can be used to dump a basic documentation file with the right structure based upon your input FITS file, and then you edit that to fill in the comments, etc.

**Comment by givoltage** [comment]
Thanks for bringing up DESI-1229. I wasn't aware many things were already defined there and simply added a row at the bottom for the FPC analysis I'm writing. These are all fits header keywords. Will update to conform to DESI-1229.

**Comment by weaverba137** [comment]
Now that protoDESI is actually on the mountain, this should really be fixed.  Please make sure that the data model actually conforms to the files to be generated and to the standards of the data model itself.

**Comment by givoltage** [comment]
I have rewritten the FPC data model doc using header dump from test images, and appended other potentially useful keywords.
Since FPC and GFA images may not be in their final shape, it is probably best to merge to protodesi branch at this point. There may be changes to HDU structure and headers before we start taking real data on sky.

**Comment by weaverba137** [comment]
The list of files in the index.rst file does not match the list of files that are actually in the PROTODESI_DATA directory.

**Comment by weaverba137** [comment]
Looks good now.  Let's get this into the "official" protodesi branch.

**Comment by givoltage** [comment]
Thanks much. I'll update the other data models as things become more finalised here on mountain. Other issues have kept the team busy.

**Pull request merged**
