### PR TITLE
Update QSO afterburner data model.

### LINKED ISSUE #110: Data model for qso afterburner files
Please review the data model for the `qso_mgii` and `qso_qn` files in *both* healpix and tiles directories. The structural description of these files should be complete, but descriptions of the HDUs, header keywords and columns need work. If necessary it is possible for files to refer to other files, or for HDUs to refer to other HDUs, to reduce duplication of effort.

### PR DESCRIPTION
**Pull request by weaverba137**
This PR closes #110.

### CODE REVIEW

**Review by weaverba137 — COMMENTED** [review]
Need to rearrange some footnotes, or come up with another solution.

**Comment by weaverba137** [comment]
@echaussidon, @sbailey, I propose that I clean up the review items and merge this myself.

**Comment by weaverba137** [comment]
I've fixed all the previous comments about footnotes.  However these files are still missing top-level summaries in the `:Summary:` section.

**Comment by echaussidon** [comment]
Hi benjamin, 

I update the file in #135. 

Sorry for the delay, I'm in vacancy these weeks.

Edmond

**Comment by weaverba137** [comment]
@echaussidon, thank you for your help with this.  In the interest of time and minimizing pull requests, I have copied your changes in #135 onto this branch.

**Pull request merged**
