### PR TITLE
New columns in description

### PR DESCRIPTION
**Pull request by aureliocarnero**
1) Add new columns in columns_description related to galaxy clustering, including the columns: PROB_OBS, BITWEIGHTS, ABSMAG_{G,R,Z}, APFLUX_{G,R,Z}, APFLUX_IVAR_{G,R,Z}, REST_GMR_0P1, KCORR_R0P1, KCORR_G0P1, ROSETTE_NUMBER, ROSETTE_R.
2) Also add the column FIBER from fba
3) Add description to NPIXELS (number of unmasked pixels contributing to the Redrock fit)
4) Add type to clustering WEIGHT columns (as float64)

### CODE REVIEW

**Review by weaverba137 — APPROVED** [review]
This looks fine to me.

**Comment by weaverba137** [comment]
@aureliocarnero, please update the change log, `doc/changes.rst`.

While we're on the topic, @ashleyjross *et al.*, is the `lssdev` branch fully inactive?

**Comment by ashleyjross** [comment]
> While we're on the topic, @ashleyjross _et al._, is the `lssdev` branch fully inactive?

I believe so. If @aureliocarnero agrees, we can delete it.

**Comment by aureliocarnero** [comment]
Yes lssdev is inactive, you can delete without problem.
I will update the Changelog first thing on Monday.
Cheers!

**Comment by aureliocarnero** [comment]
I have updated the change log in this branch. I guess it is ok, but please review and if it is correct, you can merge the pull request. Or should I do it?
Cheers
Aurelio

**Comment by weaverba137** [comment]
I'm merging now, thank you!

**Pull request merged**
