### PR TITLE
Quicklook

### PR DESCRIPTION
**Pull request by rkehoe**
Addition of data model descriptions for 5 existing QAs.  This includes algorithms after preprocessing, extraction and fiber flat steps.  Adjustments made to data model to ease combination of multiple QAs' results into single YAML files.

### CODE REVIEW

**Comment by sbailey** [comment]
Some of these tables appear to have whitespace mis-alignment, which I think ReStructuredText is picky about.  Please confirm that `python setup.py build_sphinx` is able to run without warnings and view the output in build/sphinx/html/ with a web browser to confirm that it is formatted as you intended.

For the items involving "Summed S/N", is that summing the S/N or the (S/N)^2 ?  At minimum it should be the squared version, though given that quicklook is resampling the boxcar extractions in a way that discards the pixel:pixel covariance, I don't think that the summed (S/N)^2 is a meaningful quantity either (median and mean S/N yes, but probably not the summed quantities without more exact error propagation).

**Comment by rkehoe** [comment]
I had done python setup.py test, but not build_sphinx.  That's fixed now, and files appear formatted properly.  

Summed S/N are done in quadrature.  They date from time we were considering Gaussian extraction and
are currently placeholders.  Given this comment, I want to get the correct error propagation in, and we're checking that.  For the moment, 'Tot S/N' is removed.

**Comment by sbailey** [comment]
Thanks for the format updates; merging now.

Note that the summed (S/N)^2 issue is not boxcar vs. gaussian; it is a matter of whether the data are resampled from their original extraction grid to a different grid (thus introducing pixel-to-pixel covariances) before analyzing the summed (S/N)^2.  Both boxcar and Gaussian are originally extracted on the native CCD pixel grid and then resampled in the current quicklook.  summed (S/N)^2 should be evaluated before any resampling occurs, whether or not it is boxcar of Gaussian row-by-row extractions.

**Comment by rkehoe** [comment]
Yes, I am aware of the issue with the resampling.  When thinking about Gaussian vs. boxcar, spring 2015, we explicitly considered the issue of the resampling (yes, it is not specific to Gaussian).  We did not do this in the boxcar context, but left the calculation in the list of QAs. Until we have verified correct calculations, we leave the 'tot SNR' out.

**Pull request merged**
