### PR TITLE
Rename SURVEYOPS

### LINKED ISSUE #124: Rename SURVEYOPS to DESI_SURVEYOPS
The data model directory `SURVEYOPS` actually points to the same place as `DESI_SURVEYOPS`.  In order to avoid confusion and in keeping with our convention of using environment variables as top-level directories, I propose we rename the data model directory to `DESI_SURVEYOPS`.

### PR DESCRIPTION
**Pull request by weaverba137**
This PR closes #124.

Two questions for @araichoor and @sbailey:

1. How actively is the environment variable `DESI_SURVEY` (*not* `DESI_SURVEYOPS`) used by fiberassign? In the data model, `DESI_SURVEY` is the location of intermediate fiberassign files, but `DESI_SURVEY` is not actually defined as an environment variable anywhere obvious.
2. `DESISURVEY_OUTPUT` is also not actively defined anywhere obvious, but in this case, the files will probably never be released. The [index file](https://desidatamodel.readthedocs.io/en/latest/DESISURVEY_OUTPUT/index.html) says "DESISURVEY_OUTPUT contains the outputs of desisurvey and surveysim, with the canonical location of $DESI_ROOT/survey."  But I don't actually see any of those files in `/global/cfs/cdirs/desi/survey`

### CODE REVIEW

**Comment by araichoor** [comment]
"_How actively is the environment variable DESI_SURVEY (not DESI_SURVEYOPS) used by fiberassign?_"
=>
as far as I know it s not used at all:
- I ve no recollection of ever seeing it
- as you say, it s not defined as an environmental variable when loading the desi environment:
```
raichoor@perlmutter:login10:~> godesi master
raichoor@perlmutter:login10:~> echo $DESI_
$DESI_BASIS_TEMPLATES  $DESI_ROOT             $DESI_SPECTRO_DARK     $DESI_SPECTRO_REDUX    $DESI_SURVEYOPS        $DESI_WWW              
$DESI_MOCKS            $DESI_SPECTRO_CALIB    $DESI_SPECTRO_DATA     $DESI_SPECTRO_SIM      $DESI_TARGET           
```
- it does not appear in the fiberassign code (https://github.com/desihub/fiberassign/search?q=DESI_SURVEY).

from looking at https://github.com/desihub/desidatamodel/issues/124 and https://desidatamodel.readthedocs.io/en/latest/DESI_SURVEY/index.html, I understand that it is kind of the analogous of `$DESI_ROOT/survey`, used for fiberassign "intermediate" products.
if useful, few remarks/thoughts:
- we use that folder to store the fiberassign intermediate products when we re-run the main tiles fiberassign at nersc (to assess reproducibility from the fiberassign on-the-fly at kpno, with this script https://github.com/desihub/desisurveyops/blob/main/bin/validate_lastnight_fba);
- the main files are "well-organized" there, ie following the same folder convention as the `$DESI_TARGET/fiberassign/tiles/trunk/` folder;
- for SV1, SV2, and SV3, it s more "messy", as files are organized by their creation date (things were not well-structured then); I don t know if that is a problem; if so, one option could be "artificially" recreate that structure using symlinks; however, I think I remember that there were few discrepancies there, ie that some files are not the actual files used in the end.

**Comment by schlafly** [comment]
FYI, I use DESISURVEY_OUTPUT as part of running survey simulations, but I don't see these as an especially public-facing product and have not been using that "canonical" location.  I tend to make a lot of different simulations for different use cases and it's not clear to me that a single canonical location is particularly valuable.

**Comment by weaverba137** [comment]
@sbailey, @araichoor, @schlafly, thank you for comments. I propose:

1. Keep `DESISURVEY_OUTPUT`, but remove the text about any "canonical" location.
2. Move the files currently in `DESI_SURVEY` to `DESI_ROOT/survey`.

**Comment by weaverba137** [comment]
I have implemented the `DESI_SURVEY` rename and update the text in `DESISURVEY_OUTPUT`. Last call for comments.  I'll plan on merging this later today.

**Pull request merged**
