### PR TITLE
Changes to column_descriptions related to LSS columns

### PR DESCRIPTION
**Pull request by aureliocarnero**
This pull request will resolve issues [146](https://github.com/desihub/desidatamodel/issues/148) and [148](https://github.com/desihub/desidatamodel/issues/148), related to some inconsistencies for some LSS columns. 

The exact changes applied to column_descriptions.csv are:

- Remove the following columns: sort, elg_mask, Z_not4clus, LOCFULL
- Capitalization of: lrg_mask, o2c, flux_{g,r,z,w1,w2}_dered
- Change/define types: 
                 LRG_MASK set to uint8 
                 O2C set to float64
                 LOCATION_ASSIGNED set to bool
                 IS_QSO_MGII set to bool
                 FLUX_{g,r,z,w1,w2}_DERED set to float32
- Units of FLUX_{g,r,z,w1,w2}_DERED set to nanomaggy
- Description of LOCATION_ASSIGNED: True/False for assigned/unassigned for the target in question

### CODE REVIEW

**Comment by weaverba137** [comment]
This looks fine to me, thank you for the quick update. Please merge when ready.

**Comment by weaverba137** [comment]
@aureliocarnero, merging #145 created some conflicts with your changes.  If you like, I can resolve those.

**Comment by aureliocarnero** [comment]
Yes please, if you dont mind, it would be great if you can solve it.
Cheers

**Comment by weaverba137** [comment]
OK, conflicts are resolved.  Please take a final look at the changes to confirm that everything still looks OK.

**Comment by weaverba137** [comment]
Good, thank you!

**Pull request merged**
