### PR TITLE
Summer 2017 cleanup

### PR DESCRIPTION
**Pull request by sbailey**
This PR implements some long overdue cleanup of the data model and adds the recent spectra format to the data model.

* Corrects raw data (desi), zbest, fiberassign (tile), and fibermap data models to reflect what is currently written while also noting expected future changes
* adds $DESI_SPECTRO_REDUX/SPECPROD/spectra-NSIDE/PIXGROUP/PIXNUM/spectra-NSIDE-PIXNUM.fits datamodel
* adds a mostly-empty GFA data model as a reminder
* deprecates brick grouping, while leaving datamodel around for now with a deprecation message.
* PRODNAME -> SPECPROD

I have not done an extensive review of all data model files, but this PR at least addresses some low hanging fruit of some important but obviously wrong models.

### CODE REVIEW

**Comment by weaverba137** [comment]
Some test failures are due to regular expressions not matching.  This is probably due to things like `.fits` -> `.fits.fz`.  I'm running my own tests now to find these.

Also doc/datamodel.rst needs to be added to doc/index.rst.  I can take care of that too.

**Comment by sbailey** [comment]
Crossed paths.  I was committing those fixed while you were writing the comment.  I believe they are now all fixed...

**Comment by weaverba137** [comment]
Most of the Sphinx errors are fixed, but index.rst now can't find datamodel.rst.

**Comment by weaverba137** [comment]
Looks good now.  Please merge when ready.

**Pull request merged**
