### PR TITLE
Kai revise

### PR DESCRIPTION
**Pull request by zkdtc**
Add Q and S descriptions

### CODE REVIEW

**Comment by weaverba137** [comment]
Please correct the documentation errors before merging.  See https://travis-ci.org/desihub/desidatamodel/jobs/232635037

**Comment by weaverba137** [comment]
This has been inactive for more than two weeks.  Are you still working on this?

**Comment by zkdtc** [comment]
Sorry Ben, I am totally occupied by the focal plane work now, will get back to work on this probably 1-2 weeks later. Thank you for reminding. 
                               Kai

**Comment by weaverba137** [comment]
This has been inactive for almost two months, & is now in conflict with the master branch.  How much additional work is required on this branch, not counting fixing build errors and merge conflicts?  In other words, does more content need to be added?

**Comment by weaverba137** [comment]
Attention @moustakas, @zkdtc:

This has been inactive for almost four months, & is now in conflict with the master branch. How much additional work is required on this branch, not counting fixing build errors and merge conflicts? In other words, does more content need to be added?

**Comment by moustakas** [comment]
I defer to @zkdtc -- this isn't anything I'm working on.

**Comment by weaverba137** [comment]
@zkdtc, are you still working on this?

**Comment by weaverba137** [comment]
This has been inactive for almost a year.  If I do not hear otherwise in the next few days, I will close this without merging.

**Comment by zkdtc** [comment]
Hi Ben,
   Sorry about that. Please go ahead and close it. Thank you~
                             Kai

**Comment by weaverba137** [comment]
@zkdtc, thank you for getting back to me.  Closing now.

**Pull request closed without merging**
