### PR TITLE
LSS vac datamodel

### PR DESCRIPTION
**Pull request by aureliocarnero**
The LSS vac datamodel is ready after validation from the kp3 working group. It reflects the datamodel for the EDR catalogs.

Apart from changes in the documentation in doc/DESI_ROOT/vac, there are minor changes to the data/column_descriptions.csv file, as well as a header line to the file $DESI_SURVEYOPS/mtl/sv3/dark/sv3mtl-dark-hp-HPX.rst, which we later reference in the LSS documentation.

It passed the pytest run on the lss_eda branch.

### CODE REVIEW

**Comment by weaverba137** [comment]
I ran the data model verification script
```
check_model DESI_ROOT/vac/RELEASE/lss/VERSION /global/cfs/cdirs/desi/survey/catalogs/edr_prepfor_public
```
and overall things are looking pretty good.  I have several recommendations based on that run.

1. The regular expressions you are using to match ECSV files are not working, which may explain some of item 6 below.  For example, `[0-12287]` does not match numbers in the range 0 to 12287.  It matches the single digits 0, 1, 2, 8 or 7. Since you're matching to healpixel numbers, you can use `[0-9]+` which means "any digit, one or more times".
2. `LSScats/full/fullVETO_dat.rst` describes the column `Z_RR` in HDU 1, but that column does not appear in `full/ELG_full.dat.fits`.
3. `LSScats/full/fullVETO_dat.rst` has a type mismatch in the column `ROSETTE_NUMBER`, `(float64 != int32)`.
4. `LSScats/clustering/clustering_ran.rst` has a type mismatch in `ROSETTE_NUMBER` when comparing to `LSScats/clustering/ELGnotqso_N_7_clustering.ran.fits`, `(int64 != float64)`, which is the opposite mismatch to the item above.
5. There were several cases where there were mismatches in the size of a string column, *e.g.*, `(char[51] != char[43])`. Either make sure that string columns always have the same size and put that size into the data model **or**, just use `char[*]` in the data model to signify that the size could vary and we shouldn't be concerned with that.
6. There are several data model files that could not be matched to any file on disk:
   * `potential_assignments/random/RANN/rancomb_Alltilelocinfo.rst`
   * `potential_assignments/random/RANN/rancomb_wdup_Alltiles.rst`
   * `potential_assignments/random/RANN/fba/fba.rst`
   * `potential_assignments/data/datcomb_tarwdup.rst`
   * `inputs_wspec/data/lrg+bgs_3sig_bad_fibers.rst`
   * `LSScats/nz_lss.rst`
   * `altmtl/Univ/bright/mtl-bright-hp-HPX.rst`
   * `altmtl/Univ/dark/mtl-dark-hp-HPX.rst`

**Comment by aureliocarnero** [comment]
Thank you for the detailed verification.
I will look into it asap.
Cheers

**Comment by aureliocarnero** [comment]
Dear @weaverba137 Im trying to solve these issues but Im having some problems.
In particular, in the first issue:
1) The regular expressions you are using to match ECSV files are not working, which may explain some of item 6 below. For example, [0-12287] does not match numbers in the range 0 to 12287. It matches the single digits 0, 1, 2, 8 or 7. Since you're matching to healpixel numbers, you can use [0-9]+ which means "any digit, one or more times".

For some reason, I cannot make it work. Trying to debug this, I tried to run the check module directly in the directory of interest (after setting the Regex as you suggested). But doing so Im getting two warnings: 
Im running the following code:
check_model DESI_ROOT/vac/RELEASE/lss/VERSION/altmtl/Univ/dark/ /global/cfs/cdirs/desi/survey/catalogs/edr_prepfor_public/altmtl/Univ001/dark/

Doing so, I get the following errors:
- WARNING:check.py:712:collect_files: Extraneous file detected: /global/cfs/cdirs/desi/survey/catalogs/edr_prepfor_public/altmtl/Univ001/dark/sv3mtl-dark-hp-2484.ecsv   [This for each of the files]
- WARNING:check.py:720:collect_files: No files found matching $DESIDATAMODEL/doc/DESI_ROOT/vac/RELEASE/lss/VERSION/altmtl/Univ/dark/sv3mtl-dark-hp-HPX.rst


2) In the case of Z_RR column. The problem is that this column is optional, only available for QSO. Looking into the check.py library, I see we can define optional columns like _[1]. The problem is that in this rst file, Im defining several columns that are optional, and therefore I used _[1], _[2], _[3] depending on which file they are (_[1] for LRG, _[2] for ELG and _[3] for QSO). But now reading the check.py code, I see we only define _[1] as optional.... 

I don't know what to do. Shall we allow for more numeration on optional columns? Or shall I just use _[1] for all columns and explain at the bottom which column appears for which catalog? To give you an idea of what Im thinking about, please see this page and how I deal with optional columns: https://aureliocarnero.github.io/desi_lss_datamodel.github.io/DESI_ROOT/vac/RELEASE/lss/SPECPROD/SURVEY/VERSION/LSScats/full/fullVETO_dat.html

**Comment by aureliocarnero** [comment]
By the way, the Regex rule we were using for the ECSV files was just a copy of 
https://github.com/desihub/desidatamodel/blob/main/doc/DESI_SURVEYOPS/mtl/sv3/dark/sv3mtl-dark-hp-HPX.rst
So I guess this won't work either...

**Comment by aureliocarnero** [comment]
Another issue that Im suspicious about is how the check_model works, when the rst files are under a generic path, which reflects a list of directories. For example, in the LSS datamodel, we define a directory called Univ, which actually corresponds to 128 directories in the data. i.e., in the data, we have Univ001, Univ002 ....  

The same with potential_assignments/random/RANN, where RANN is a number going from 00 to 17...

Is it possible that there is some confusion in the code and it is not interpreting correctly where to look for the files that might match the rst files?

**Comment by weaverba137** [comment]
@aureliocarnero, I believe you might be right and that the directory path is causing the issue, not the regular expression.  I can fix that, but it has to be fixed in the data model code.

**Comment by weaverba137** [comment]
On other topics: You can use `[1]_` as many times as you need to in a file, and only have a single
```
.. _[1] Optional
```
that it points to. There are examples of this elsewhere if you need it, such as the [ztile catalog](https://github.com/desihub/desidatamodel/blob/main/doc/DESI_SPECTRO_REDUX/SPECPROD/zcatalog/ztile-SURVEY-PROGRAM-GROUPTYPE.rst).

**Comment by weaverba137** [comment]
@aureliocarnero, you will need to pick up my changes before proceeding further.  It looks like maybe you updated some of the regular expressions and optional flags, but didn't check in those changes?

**Pull request closed without merging**
