### PR TITLE
Migrate units to desiutil

### LINKED ISSUE #184: Formatting issue of PHOTSYS description
Currently the PHOTSYS description is
`&#x27;N&#x27; for the MzLS/BASS photometric system, &#x27;S&#x27; for DECaLS`
in https://desidatamodel.readthedocs.io/en/latest/DESI_SPECTRO_REDUX/SPECPROD/healpix/SURVEY/PROGRAM/PIXGROUP/PIXNUM/coadd-SURVEY-PROGRAM-PIXNUM.html and in many other places.

### LINKED ISSUE #185: Migrate unit verification code to desiutil
To further enable desihub/desiutil#191, unit verification code should be moved to desiutil and then imported from there.

During the transition period, keep a fall-back copy of the code in desidatamodel in case desidatamodel has an older version of desiutil in its environment.

### PR DESCRIPTION
**Pull request by weaverba137**
This PR is a companion to desihub/desiutil#201. It simply imports the unit verification code from desiutil, but if for some reason there is an older version of desiutil in its environment, it falls back on built-in code. Eventually this can be removed.

I want to run a few more operational tests before merging.

* Closes #184.
* Closes #185.

### CODE REVIEW

**Comment by weaverba137** [comment]
Note for reviewers: a lot of files changed, but that's because issue #184 was quite widespread.

**Comment by weaverba137** [comment]
@sbailey, this is ready for review.

**Comment by weaverba137** [comment]
@sbailey, if you want to review this, that's great, but I don't think there's anything controversial here, despite the number of files changed.

**Comment by sbailey** [comment]
Thanks, this looks fine.  In cases like this you are welcome to self merge.  Thanks for fixing all those `&#x27;` quotes.

**Pull request merged**
