### PR TITLE
Quicklook

### PR DESCRIPTION
**Pull request by rkehoe**
Several updates to prepare for test stand and further Sim testing:

- QA 'xwsigma' to provide line width in preprocessed image around selected peak sky wavelengths
- QA 'sky peak' to examine peaks at selected peak wavelengths of sky (after flattening)
- QA 'integ' to provide integral counts per STAR spectra

Updates were also prepared for several existing QAs, including:

- S/N vs. magnitude for each tracer/STAR type
- MJD to ISO style 'QATIME' key (to aid QLF monitoring of pipeline)
- noise estimate in overscan region
- good fiber count

Note: for S/N vs. magnitude, only DECCam 'r' is used currently.  Magnitude set for moment to -1.0 if not available.

### CODE REVIEW

**Comment by weaverba137** [comment]
I don't see any significant problems with this.  @rkehoe is this completely ready to merge?

**Comment by weaverba137** [comment]
Paging @rkehoe. Any further work that needs to be done on this PR?

**Comment by rkehoe** [comment]
@weaverba137 yes this was ready to merge, but now I have added additional QA data model for sky residuals.  This is ready to merge pending your check.

**Comment by weaverba137** [comment]
Thanx, merging now.

**Pull request merged**
