### PR TITLE
fix column name

### PR DESCRIPTION
**Pull request by segasai**
Hi,

The column name seems incorrect PSF_TO_FIBER_SPECFLUX instead of PSF_TO_FIBER_FLUX. The patch fixes that.

 S

### CODE REVIEW

**Comment by weaverba137** [comment]
Could you please give an example file that has this column name? The data model was previously tested on EDR, so if this is something new, that's fine, but we need to verify that.

**Comment by segasai** [comment]
I think the problem was in the EDR as well, as I can see it in fuji and iron (and jura):
/global/cfs/cdirs/desi/spectro/redux/fuji/exposures/20210116/00072716/fluxcalib-z6-00072716.fits
/global/cfs/cdirs/desi/spectro/redux/iron/exposures/20211114/00108766/fluxcalib-r9-00108766.fits.gz

**Comment by weaverba137** [comment]
Thank you, I will have to investigate further. It is possible that both column names are present in a given specprod.

**Comment by weaverba137** [comment]
OK, I see what you're doing now. Thank you for noticing this.  Merging now.

**Pull request merged**
