### PR TITLE
Lss EDR datamodel release

### PR DESCRIPTION
**Pull request by aureliocarnero**
Im redoing the pull request for the LSS datamodel.
I have run the check_model script to correct all the issues identified in the previous request. 
There is still one issue I don't know to solve. Even though the check_model don't identify any Extraneous file, those files that are not fits (ecsv or ascii) still rise an error. 
For the couple of ascii files, it tells me that "No files found matching rst file!".
For the ecsv files, it tells me "No useful prototype files found for rst file"

Also, there are some weird errors in a couple of ecsv files I don't understand why it is rising an error, when there are hundreds of files similar to this, but for a couple, it does complaint.

Here the output of check_model:

WARNING:check.py:724:collect_files: No files found matching /global/homes/a/acarnero/codes/desidatamodel/doc/DESI_ROOT/vac/RELEASE/lss/VERSION/inputs_wspec/data/lrg+bgs_3sig_bad_fibers.rst!
WARNING:check.py:724:collect_files: No files found matching /global/homes/a/acarnero/codes/desidatamodel/doc/DESI_ROOT/vac/RELEASE/lss/VERSION/LSScats/nz_lss.rst!
WARNING:check.py:470:validate_prototype: Error opening /global/cfs/cdirs/desi/survey/catalogs/edr_prepfor_public/altmtl/Univ061/bright/sv3mtl-bright-hp-6477.ecsv, skipping to next candidate.
WARNING:check.py:471:validate_prototype: Message was: 'No SIMPLE card found, this file does not appear to be a valid FITS file. If this is really a FITS file, try with ignore_missing_simple=True'.
WARNING:check.py:470:validate_prototype: Error opening /global/cfs/cdirs/desi/survey/catalogs/edr_prepfor_public/altmtl/Univ061/bright/sv3mtl-bright-hp-6511.ecsv, skipping to next candidate.
WARNING:check.py:471:validate_prototype: Message was: 'No SIMPLE card found, this file does not appear to be a valid FITS file. If this is really a FITS file, try with ignore_missing_simple=True'.
WARNING:check.py:470:validate_prototype: Error opening /global/cfs/cdirs/desi/survey/catalogs/edr_prepfor_public/altmtl/Univ061/bright/sv3mtl-bright-hp-6741.ecsv, skipping to next candidate.
WARNING:check.py:471:validate_prototype: Message was: 'No SIMPLE card found, this file does not appear to be a valid FITS file. If this is really a FITS file, try with ignore_missing_simple=True'.
WARNING:check.py:470:validate_prototype: Error opening /global/cfs/cdirs/desi/survey/catalogs/edr_prepfor_public/altmtl/Univ061/bright/sv3mtl-bright-hp-2481.ecsv, skipping to next candidate.
WARNING:check.py:471:validate_prototype: Message was: 'No SIMPLE card found, this file does not appear to be a valid FITS file. If this is really a FITS file, try with ignore_missing_simple=True'.
WARNING:check.py:470:validate_prototype: Error opening /global/cfs/cdirs/desi/survey/catalogs/edr_prepfor_public/altmtl/Univ061/bright/sv3mtl-bright-hp-6493.ecsv, skipping to next candidate.
WARNING:check.py:471:validate_prototype: Message was: 'No SIMPLE card found, this file does not appear to be a valid FITS file. If this is really a FITS file, try with ignore_missing_simple=True'.
ERROR:check.py:483:validate_prototype: No useful prototype files found for /global/homes/a/acarnero/codes/desidatamodel/doc/DESI_ROOT/vac/RELEASE/lss/VERSION/altmtl/UnivUNUM/bright/sv3mtl-bright-hp-HPX.rst!
WARNING:check.py:470:validate_prototype: Error opening /global/cfs/cdirs/desi/survey/catalogs/edr_prepfor_public/altmtl/Univ061/dark/sv3mtl-dark-hp-2357.ecsv, skipping to next candidate.
WARNING:check.py:471:validate_prototype: Message was: 'No SIMPLE card found, this file does not appear to be a valid FITS file. If this is really a FITS file, try with ignore_missing_simple=True'.
WARNING:check.py:470:validate_prototype: Error opening /global/cfs/cdirs/desi/survey/catalogs/edr_prepfor_public/altmtl/Univ061/dark/sv3mtl-dark-hp-2602.ecsv, skipping to next candidate.
WARNING:check.py:471:validate_prototype: Message was: 'No SIMPLE card found, this file does not appear to be a valid FITS file. If this is really a FITS file, try with ignore_missing_simple=True'.
WARNING:check.py:470:validate_prototype: Error opening /global/cfs/cdirs/desi/survey/catalogs/edr_prepfor_public/altmtl/Univ061/dark/sv3mtl-dark-hp-4011.ecsv, skipping to next candidate.
WARNING:check.py:471:validate_prototype: Message was: 'No SIMPLE card found, this file does not appear to be a valid FITS file. If this is really a FITS file, try with ignore_missing_simple=True'.
WARNING:check.py:470:validate_prototype: Error opening /global/cfs/cdirs/desi/survey/catalogs/edr_prepfor_public/altmtl/Univ061/dark/sv3mtl-dark-hp-2286.ecsv, skipping to next candidate.
WARNING:check.py:471:validate_prototype: Message was: 'No SIMPLE card found, this file does not appear to be a valid FITS file. If this is really a FITS file, try with ignore_missing_simple=True'.
WARNING:check.py:470:validate_prototype: Error opening /global/cfs/cdirs/desi/survey/catalogs/edr_prepfor_public/altmtl/Univ061/dark/sv3mtl-dark-hp-2630.ecsv, skipping to next candidate.
WARNING:check.py:471:validate_prototype: Message was: 'No SIMPLE card found, this file does not appear to be a valid FITS file. If this is really a FITS file, try with ignore_missing_simple=True'.
ERROR:check.py:483:validate_prototype: No useful prototype files found for /global/homes/a/acarnero/codes/desidatamodel/doc/DESI_ROOT/vac/RELEASE/lss/VERSION/altmtl/UnivUNUM/dark/sv3mtl-dark-hp-HPX.rst!

### CODE REVIEW

**Comment by weaverba137** [comment]
Could you explain in more detail why a separate PR was needed? There were not actually any problems with the old one.

**Comment by weaverba137** [comment]
You can ignore warnings like this:
```
WARNING:check.py:471:validate_prototype: Message was: 'No SIMPLE card found, this file does not appear to be a valid FITS file. If this is really a FITS file, try with ignore_missing_simple=True'.
```

**Comment by weaverba137** [comment]
Just to be explicit, it looks like the *only* remaining warnings to be concerned about are these:
```
WARNING:check.py:724:collect_files: No files found matching /global/common/software/desi/users/bweaver/perlmutter/desiconda/current/code/desidatamodel/my-main/doc/DESI_ROOT/vac/RELEASE/lss/VERSION/inputs_wspec/data/lrg+bgs_3sig_bad_fibers.rst!
WARNING:check.py:724:collect_files: No files found matching /global/common/software/desi/users/bweaver/perlmutter/desiconda/current/code/desidatamodel/my-main/doc/DESI_ROOT/vac/RELEASE/lss/VERSION/LSScats/nz_lss.rst!
```
I'll focus on those.

**Comment by aureliocarnero** [comment]
Cool! Thanks. I didn't know about the special characters in regex. I see "+" and "." needs to be with \.
Well spot! Thank you

**Comment by weaverba137** [comment]
I'm not done yet, but that did need to be fixed.

**Comment by weaverba137** [comment]
OK, everything matches now. If there are no further content changes planned, I think this is ready to merge.

**Comment by aureliocarnero** [comment]
There is no more changes. You can proceed with the request. Thank you

**Pull request merged**
